# Generated by Django 4.1 on 2022-08-25 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('code', models.IntegerField(verbose_name='Код')),
                ('phone', models.CharField(max_length=11, verbose_name='Номер телефона')),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=255, verbose_name='Отчество')),
                ('data', models.DateField(null=True, verbose_name='Дата рождения')),
                ('phone', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер телефона')),
                ('health', models.CharField(blank=True, default='Практически здоров', help_text='аллергоанамнез, хронические заболевания и т.п.', max_length=255, verbose_name='Состояние здоровья')),
                ('gender', models.CharField(choices=[('M', 'Man'), ('W', 'Woman')], default='M', max_length=1, verbose_name='Ваш пол')),
                ('image', models.ImageField(blank=True, upload_to='project/media')),
            ],
            options={
                'ordering': ('surname', 'name', 'patronymic'),
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now=True, verbose_name='Дата обращения')),
                ('number', models.IntegerField(blank=True, db_index=True, editable=False, unique=True, verbose_name='Номер обращения')),
                ('victims', models.PositiveSmallIntegerField(blank=True, verbose_name='Количество пострадавших')),
                ('call', models.BooleanField(default=True, verbose_name='Звонок')),
                ('status', models.CharField(choices=[('in_work', 'В работе'), ('completed', 'Завершено')], default='in_work', max_length=255)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Incidents', to='core.person')),
                ('service', models.ManyToManyField(null=True, related_name='Incidents', to='core.emergencyservice')),
            ],
            options={
                'ordering': ('data', 'number'),
            },
        ),
        migrations.AddField(
            model_name='emergencyservice',
            name='appeal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EmergencyServices', to='core.person'),
        ),
    ]
