# Generated by Django 4.1 on 2022-08-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyservice',
            name='code',
            field=models.IntegerField(help_text='01-Пожарная служба, 02-Полиция, 03-Скорая помощь', verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='number',
            field=models.IntegerField(blank=True, db_index=True, editable=False, null=True, unique=True, verbose_name='Номер обращения'),
        ),
    ]
