# Generated by Django 4.1 on 2022-08-30 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_emergencyservice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ('date', 'number'), 'verbose_name': 'Обращения'},
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='data',
            new_name='date',
        ),
    ]
