# Generated by Django 4.1 on 2022-08-31 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_incident_options_rename_data_incident_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyservice',
            name='code',
            field=models.IntegerField(help_text='01-Пожарная служба, 02-Полиция, 03-Скорая помощь',
                                      null=True,
                                      verbose_name='Код'),
        ),
    ]
