# Generated by Django 4.1 on 2022-09-14 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_emergencyservice_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergencyservice',
            options={'ordering': ('code',), 'verbose_name': 'Экстренные службы', 'verbose_name_plural': 'Экстренные службы'},
        ),
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ('date', 'number'), 'verbose_name': 'Обращения', 'verbose_name_plural': 'Обращения'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('surname', 'name', 'patronymic'), 'verbose_name': 'Заявитель', 'verbose_name_plural': 'Заявитель'},
        ),
    ]
