# Generated by Django 4.1 on 2022-09-17 17:56

from django.core.management import call_command
from django.db import migrations


def load_data(apps, schema_editor):  # noqa
    call_command('loaddata', 'person.json')
    call_command('loaddata', 'service.json')
    call_command('loaddata', 'incident.json')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_emergencyservice_options_and_more'),
    ]

    operations = [
        migrations.RunPython(code=load_data, reverse_code=lambda a, s: 1)
    ]
